use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use image::imageops::FilterType;
use image::GenericImageView;

// Target pixel size of the cached tray-icon frames. The macOS menubar runs at
// roughly 22pt; 44px = 2x retina backing. The native_tray CALayer is sized to
// 22x22pt and uses kCAGravityCenter at contentsScale=2.0, so this matches the
// physical pixel grid exactly — no GPU resampling per swap.
const TARGET_SIZE: u32 = 44;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let icons_dir = manifest_dir.join("icons");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=icons");
    println!("cargo:rerun-if-changed=icons/tray-icon.png");

    let generated = generate_frames(&icons_dir, &manifest_dir, &out_dir);
    fs::write(out_dir.join("frames.rs"), generated).expect("write frames.rs");

    tauri_build::build()
}

fn generate_frames(icons_dir: &Path, manifest_dir: &Path, out_dir: &Path) -> String {
    let mut out = String::from("// auto-generated by build.rs — do not edit\n\n");

    let mut anim_dirs: Vec<_> = fs::read_dir(icons_dir)
        .expect("read icons dir")
        .filter_map(|e| e.ok())
        .filter(|e| {
            let is_dir = e.file_type().map(|t| t.is_dir()).unwrap_or(false);
            let name = e.file_name().to_string_lossy().to_string();
            is_dir && (name == "anim" || name.starts_with("anim-"))
        })
        .collect();
    anim_dirs.sort_by_key(|e| e.file_name());

    for entry in anim_dirs {
        let dir_name = entry.file_name().to_string_lossy().to_string();
        let dir_path = entry.path();
        println!("cargo:rerun-if-changed={}", dir_path.display());

        let mut frames: Vec<String> = fs::read_dir(&dir_path)
            .expect("read anim dir")
            .filter_map(|e| e.ok())
            .filter_map(|e| {
                let name = e.file_name().to_string_lossy().to_string();
                (name.starts_with("frame-") && name.ends_with(".png")).then_some(name)
            })
            .collect();
        frames.sort();

        if frames.is_empty() {
            panic!("no frame-*.png files in icons/{}", dir_name);
        }

        let ident = dir_name.replace('-', "_");
        let upper = ident.to_uppercase();
        out.push_str(&format!("pub const {}_LEN: usize = {};\n", upper, frames.len()));
        out.push_str(&format!(
            "pub fn {}(idx: usize) -> tauri::image::Image<'static> {{\n",
            ident
        ));
        out.push_str(&format!("    match idx % {}_LEN {{\n", upper));
        for (i, f) in frames.iter().enumerate() {
            let path = format!("icons/{}/{}", dir_name, f);
            if i + 1 == frames.len() {
                out.push_str(&format!(
                    "        _ => tauri::include_image!(\"{}\"),\n",
                    path
                ));
            } else {
                out.push_str(&format!(
                    "        {} => tauri::include_image!(\"{}\"),\n",
                    i, path
                ));
            }
        }
        out.push_str("    }\n}\n\n");

        // Pre-scale every frame to TARGET_SIZE x TARGET_SIZE premultiplied RGBA,
        // write to OUT_DIR/<dir>/frame-XX.rgba, and emit a function returning
        // the bytes. native_tray.rs wraps each in a CGImage at startup.
        let rgba_out_dir = out_dir.join(&dir_name);
        fs::create_dir_all(&rgba_out_dir).expect("create rgba out dir");
        for f in &frames {
            let src_path = manifest_dir.join("icons").join(&dir_name).join(f);
            let img = image::open(&src_path)
                .unwrap_or_else(|e| panic!("decode {}: {}", src_path.display(), e));
            let (w, h) = img.dimensions();
            // Square fit: scale longest side to TARGET_SIZE.
            let scale = TARGET_SIZE as f32 / w.max(h) as f32;
            let nw = ((w as f32 * scale).round() as u32).max(1);
            let nh = ((h as f32 * scale).round() as u32).max(1);
            let resized = image::imageops::resize(&img.to_rgba8(), nw, nh, FilterType::Lanczos3);
            // Center into a TARGET_SIZE x TARGET_SIZE canvas.
            let mut canvas = image::RgbaImage::new(TARGET_SIZE, TARGET_SIZE);
            let ox = (TARGET_SIZE - nw) / 2;
            let oy = (TARGET_SIZE - nh) / 2;
            image::imageops::overlay(&mut canvas, &resized, ox as i64, oy as i64);
            // CoreGraphics with kCGImageAlphaPremultipliedLast expects premul.
            for px in canvas.pixels_mut() {
                let a = px.0[3] as u32;
                if a < 255 {
                    px.0[0] = ((px.0[0] as u32 * a + 127) / 255) as u8;
                    px.0[1] = ((px.0[1] as u32 * a + 127) / 255) as u8;
                    px.0[2] = ((px.0[2] as u32 * a + 127) / 255) as u8;
                }
            }
            let raw_name = f.replace(".png", ".rgba");
            let raw_path = rgba_out_dir.join(&raw_name);
            fs::write(&raw_path, canvas.as_raw()).expect("write rgba");
        }

        out.push_str(&format!(
            "pub fn {}_rgba(idx: usize) -> &'static [u8] {{\n",
            ident
        ));
        out.push_str(&format!("    match idx % {}_LEN {{\n", upper));
        for (i, f) in frames.iter().enumerate() {
            let raw_name = f.replace(".png", ".rgba");
            let abs = rgba_out_dir.join(&raw_name).to_string_lossy().to_string();
            if i + 1 == frames.len() {
                out.push_str(&format!("        _ => include_bytes!(r#\"{}\"#),\n", abs));
            } else {
                out.push_str(&format!("        {} => include_bytes!(r#\"{}\"#),\n", i, abs));
            }
        }
        out.push_str("    }\n}\n\n");
    }

    out.push_str(&format!(
        "pub const TRAY_FRAME_PX: u32 = {};\n",
        TARGET_SIZE
    ));

    out
}
